### ISSUE TITLE
error handling on idle task manager

### ISSUE THREAD

**Issue by caperaven** [caperaven/crs-binding#6]
There was a scenario where a function in the idle task manager failed.
This failure prevented the further processing of tasks in the manager's collection.
Add better error handling on the idle task manager.

**Comment by Ashton-Pragma** [comment]
I have a test on the client commented out because of this issue, just waiting for a binding engine update @gerhardmeyer

**Comment by caperaven** [comment]
@Ashton-Pragma we also need to bring in the new templates registry in to deal with some performance issues we had on lists. Should be updating the new version next sprint.
